/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaskFrequency = IDL.Variant({
  'monthly' : IDL.Null,
  'daily' : IDL.Null,
  'weekly' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'manager' : IDL.Null,
  'assistant' : IDL.Null,
});
export const Language = IDL.Variant({
  'french' : IDL.Null,
  'dutch' : IDL.Null,
  'english' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'username' : IDL.Text,
  'role' : UserRole,
  'language' : Language,
});
export const AuditLogAction = IDL.Variant({
  'taskUpdated' : IDL.Null,
  'taskCreated' : IDL.Null,
  'taskMarkedDone' : IDL.Null,
});
export const Time = IDL.Int;
export const TaskHistoryEntry = IDL.Record({
  'id' : IDL.Nat,
  'action' : AuditLogAction,
  'username' : IDL.Text,
  'summary' : IDL.Text,
  'taskId' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
  'completionComment' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'evidencePhotoPath' : IDL.Opt(IDL.Text),
});
export const ToDoTask = IDL.Record({
  'id' : IDL.Nat,
  'completedBy' : IDL.Opt(IDL.Principal),
  'title' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'lastCompleted' : IDL.Opt(Time),
  'isWeekly' : IDL.Bool,
  'description' : IDL.Text,
  'completionComment' : IDL.Opt(IDL.Text),
  'completedByUsername' : IDL.Opt(IDL.Text),
  'frequency' : TaskFrequency,
  'evidencePhotoPath' : IDL.Opt(IDL.Text),
  'completionTimestamp' : IDL.Opt(Time),
  'isPinned' : IDL.Bool,
});
export const AuditLogEntry = IDL.Record({
  'action' : AuditLogAction,
  'username' : IDL.Text,
  'taskId' : IDL.Nat,
  'userPrincipal' : IDL.Principal,
  'timestamp' : Time,
  'changeSummary' : IDL.Text,
});
export const OvertimeEntry = IDL.Record({
  'date' : IDL.Text,
  'minutes' : IDL.Nat,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'isAdd' : IDL.Bool,
});
export const OvertimeTotals = IDL.Record({
  'totalHours' : IDL.Nat,
  'totalDays' : IDL.Nat,
  'totalMinutes' : IDL.Nat,
});
export const TaskPreference = IDL.Variant({
  'hated' : IDL.Null,
  'preferred' : IDL.Null,
  'neutral' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'checkManagerNotifications' : IDL.Func([], [IDL.Bool], []),
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, TaskFrequency, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteAssistantData' : IDL.Func([IDL.Principal], [], []),
  'getAllAssistants' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllTaskHistory' : IDL.Func([], [IDL.Vec(TaskHistoryEntry)], ['query']),
  'getAllTaskHistoryEntries' : IDL.Func(
      [],
      [IDL.Vec(TaskHistoryEntry)],
      ['query'],
    ),
  'getAllTasks' : IDL.Func([], [IDL.Vec(ToDoTask)], ['query']),
  'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getOvertimeEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(OvertimeEntry)],
      ['query'],
    ),
  'getOvertimeTotals' : IDL.Func([IDL.Text], [OvertimeTotals], ['query']),
  'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(ToDoTask)], ['query']),
  'getTaskHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TaskHistoryEntry)],
      ['query'],
    ),
  'getTaskPreferences' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, TaskPreference))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logOvertime' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Bool], [], []),
  'markTaskDone' : IDL.Func(
      [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'registerAssistant' : IDL.Func([IDL.Text, Language], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setTaskPinnedStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setTaskPreference' : IDL.Func([IDL.Text, IDL.Nat, TaskPreference], [], []),
  'updateTask' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, TaskFrequency, IDL.Bool],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaskFrequency = IDL.Variant({
    'monthly' : IDL.Null,
    'daily' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'manager' : IDL.Null,
    'assistant' : IDL.Null,
  });
  const Language = IDL.Variant({
    'french' : IDL.Null,
    'dutch' : IDL.Null,
    'english' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'username' : IDL.Text,
    'role' : UserRole,
    'language' : Language,
  });
  const AuditLogAction = IDL.Variant({
    'taskUpdated' : IDL.Null,
    'taskCreated' : IDL.Null,
    'taskMarkedDone' : IDL.Null,
  });
  const Time = IDL.Int;
  const TaskHistoryEntry = IDL.Record({
    'id' : IDL.Nat,
    'action' : AuditLogAction,
    'username' : IDL.Text,
    'summary' : IDL.Text,
    'taskId' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
    'completionComment' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'evidencePhotoPath' : IDL.Opt(IDL.Text),
  });
  const ToDoTask = IDL.Record({
    'id' : IDL.Nat,
    'completedBy' : IDL.Opt(IDL.Principal),
    'title' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'lastCompleted' : IDL.Opt(Time),
    'isWeekly' : IDL.Bool,
    'description' : IDL.Text,
    'completionComment' : IDL.Opt(IDL.Text),
    'completedByUsername' : IDL.Opt(IDL.Text),
    'frequency' : TaskFrequency,
    'evidencePhotoPath' : IDL.Opt(IDL.Text),
    'completionTimestamp' : IDL.Opt(Time),
    'isPinned' : IDL.Bool,
  });
  const AuditLogEntry = IDL.Record({
    'action' : AuditLogAction,
    'username' : IDL.Text,
    'taskId' : IDL.Nat,
    'userPrincipal' : IDL.Principal,
    'timestamp' : Time,
    'changeSummary' : IDL.Text,
  });
  const OvertimeEntry = IDL.Record({
    'date' : IDL.Text,
    'minutes' : IDL.Nat,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'isAdd' : IDL.Bool,
  });
  const OvertimeTotals = IDL.Record({
    'totalHours' : IDL.Nat,
    'totalDays' : IDL.Nat,
    'totalMinutes' : IDL.Nat,
  });
  const TaskPreference = IDL.Variant({
    'hated' : IDL.Null,
    'preferred' : IDL.Null,
    'neutral' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'checkManagerNotifications' : IDL.Func([], [IDL.Bool], []),
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, TaskFrequency, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteAssistantData' : IDL.Func([IDL.Principal], [], []),
    'getAllAssistants' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllTaskHistory' : IDL.Func([], [IDL.Vec(TaskHistoryEntry)], ['query']),
    'getAllTaskHistoryEntries' : IDL.Func(
        [],
        [IDL.Vec(TaskHistoryEntry)],
        ['query'],
      ),
    'getAllTasks' : IDL.Func([], [IDL.Vec(ToDoTask)], ['query']),
    'getAuditLog' : IDL.Func([], [IDL.Vec(AuditLogEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getOvertimeEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(OvertimeEntry)],
        ['query'],
      ),
    'getOvertimeTotals' : IDL.Func([IDL.Text], [OvertimeTotals], ['query']),
    'getTask' : IDL.Func([IDL.Nat], [IDL.Opt(ToDoTask)], ['query']),
    'getTaskHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TaskHistoryEntry)],
        ['query'],
      ),
    'getTaskPreferences' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, TaskPreference))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logOvertime' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text, IDL.Bool], [], []),
    'markTaskDone' : IDL.Func(
        [IDL.Nat, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'registerAssistant' : IDL.Func([IDL.Text, Language], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setTaskPinnedStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setTaskPreference' : IDL.Func([IDL.Text, IDL.Nat, TaskPreference], [], []),
    'updateTask' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, TaskFrequency, IDL.Bool],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };