/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AssistantTaskCompletionRecord {
  'completedOnTime' : boolean,
  'taskTitle' : string,
  'taskId' : bigint,
  'frequency' : TaskFrequency,
  'completionTimestamp' : Time,
}
export interface AssistantTaskHabits {
  'completions' : Array<AssistantTaskCompletionRecord>,
  'summary' : AssistantTaskSummary,
}
export interface AssistantTaskSummary {
  'dailyTasks' : bigint,
  'totalTasks' : bigint,
  'username' : string,
  'completedTasks' : bigint,
  'taskPreferences' : Array<[bigint, TaskPreference]>,
  'weeklyTasks' : bigint,
  'monthlyTasks' : bigint,
  'onTimeTasks' : bigint,
}
export type AuditLogAction = { 'taskUpdated' : null } |
  { 'taskCreated' : null } |
  { 'taskMarkedDone' : null };
export interface AuditLogEntry {
  'action' : AuditLogAction,
  'username' : string,
  'taskId' : bigint,
  'userPrincipal' : Principal,
  'timestamp' : Time,
  'changeSummary' : string,
}
export type Language = { 'french' : null } |
  { 'dutch' : null } |
  { 'english' : null };
export interface OvertimeEntry {
  'date' : string,
  'minutes' : bigint,
  'comment' : string,
  'timestamp' : Time,
  'isAdd' : boolean,
}
export interface OvertimeTotals {
  'totalHours' : bigint,
  'totalDays' : bigint,
  'totalMinutes' : bigint,
}
export type TaskFrequency = { 'monthly' : null } |
  { 'daily' : null } |
  { 'weekly' : null };
export interface TaskHistoryEntry {
  'id' : bigint,
  'action' : AuditLogAction,
  'username' : string,
  'completedOnTime' : [] | [boolean],
  'summary' : string,
  'taskId' : bigint,
  'userPrincipal' : Principal,
  'completionComment' : [] | [string],
  'timestamp' : Time,
  'evidencePhotoPath' : [] | [string],
}
export type TaskPreference = { 'hated' : null } |
  { 'preferred' : null } |
  { 'neutral' : null };
export type Time = bigint;
export interface ToDoTask {
  'id' : bigint,
  'completedBy' : [] | [Principal],
  'title' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'lastCompleted' : [] | [Time],
  'isWeekly' : boolean,
  'description' : string,
  'completionComment' : [] | [string],
  'completedByUsername' : [] | [string],
  'frequency' : TaskFrequency,
  'evidencePhotoPath' : [] | [string],
  'completionTimestamp' : [] | [Time],
  'isPinned' : boolean,
}
export interface UserProfile {
  'principal' : Principal,
  'username' : string,
  'role' : UserRole,
  'language' : Language,
}
export type UserRole = { 'manager' : null } |
  { 'assistant' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'checkManagerNotifications' : ActorMethod<[], boolean>,
  'createTask' : ActorMethod<[string, string, TaskFrequency, boolean], bigint>,
  'deleteAssistantData' : ActorMethod<[Principal], undefined>,
  'getAllAssistants' : ActorMethod<[], Array<UserProfile>>,
  'getAllTaskHistory' : ActorMethod<[], Array<TaskHistoryEntry>>,
  'getAllTaskHistoryEntries' : ActorMethod<[], Array<TaskHistoryEntry>>,
  'getAllTasks' : ActorMethod<[], Array<ToDoTask>>,
  'getAssistantTaskHabits' : ActorMethod<[string], AssistantTaskHabits>,
  'getAuditLog' : ActorMethod<[], Array<AuditLogEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getOvertimeEntries' : ActorMethod<[string], Array<OvertimeEntry>>,
  'getOvertimeTotals' : ActorMethod<[string], OvertimeTotals>,
  'getTask' : ActorMethod<[bigint], [] | [ToDoTask]>,
  'getTaskHistory' : ActorMethod<[bigint], Array<TaskHistoryEntry>>,
  'getTaskPreferences' : ActorMethod<[string], Array<[bigint, TaskPreference]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logOvertime' : ActorMethod<[string, bigint, string, boolean], undefined>,
  'markTaskDone' : ActorMethod<
    [bigint, [] | [string], [] | [string]],
    undefined
  >,
  'registerAssistant' : ActorMethod<[string, Language], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setTaskPinnedStatus' : ActorMethod<[bigint, boolean], undefined>,
  'setTaskPreference' : ActorMethod<
    [string, bigint, TaskPreference],
    undefined
  >,
  'updateTask' : ActorMethod<
    [bigint, string, string, TaskFrequency, boolean],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];