/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface OvertimeEntry {
    date: string;
    minutes: bigint;
    comment: string;
    timestamp: Time;
    isAdd: boolean;
}
export interface OvertimeTotals {
    totalHours: bigint;
    totalDays: bigint;
    totalMinutes: bigint;
}
export interface ToDoTask {
    id: bigint;
    completedBy?: Principal;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    lastCompleted?: Time;
    isWeekly: boolean;
    description: string;
    completionComment?: string;
    completedByUsername?: string;
    frequency: TaskFrequency;
    evidencePhotoPath?: string;
    completionTimestamp?: Time;
    isPinned: boolean;
}
export interface AuditLogEntry {
    action: AuditLogAction;
    username: string;
    taskId: bigint;
    userPrincipal: Principal;
    timestamp: Time;
    changeSummary: string;
}
export interface TaskHistoryEntry {
    id: bigint;
    action: AuditLogAction;
    username: string;
    summary: string;
    taskId: bigint;
    userPrincipal: Principal;
    completionComment?: string;
    timestamp: Time;
    evidencePhotoPath?: string;
}
export interface UserProfile {
    principal: Principal;
    username: string;
    role: UserRole;
    language: Language;
}
export enum AuditLogAction {
    taskUpdated = "taskUpdated",
    taskCreated = "taskCreated",
    taskMarkedDone = "taskMarkedDone"
}
export enum Language {
    french = "french",
    dutch = "dutch",
    english = "english"
}
export enum TaskFrequency {
    monthly = "monthly",
    daily = "daily",
    weekly = "weekly"
}
export enum TaskPreference {
    hated = "hated",
    preferred = "preferred",
    neutral = "neutral"
}
export enum UserRole {
    manager = "manager",
    assistant = "assistant"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    checkManagerNotifications(): Promise<boolean>;
    createTask(title: string, description: string, frequency: TaskFrequency, isWeekly: boolean): Promise<bigint>;
    deleteAssistantData(assistantPrincipal: Principal): Promise<void>;
    getAllAssistants(): Promise<Array<UserProfile>>;
    getAllTaskHistory(): Promise<Array<TaskHistoryEntry>>;
    getAllTaskHistoryEntries(): Promise<Array<TaskHistoryEntry>>;
    getAllTasks(): Promise<Array<ToDoTask>>;
    getAuditLog(): Promise<Array<AuditLogEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getOvertimeEntries(username: string): Promise<Array<OvertimeEntry>>;
    getOvertimeTotals(username: string): Promise<OvertimeTotals>;
    getTask(taskId: bigint): Promise<ToDoTask | null>;
    getTaskHistory(taskId: bigint): Promise<Array<TaskHistoryEntry>>;
    getTaskPreferences(assistantUsername: string): Promise<Array<[bigint, TaskPreference]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    logOvertime(date: string, minutes: bigint, comment: string, isAdd: boolean): Promise<void>;
    markTaskDone(taskId: bigint, evidencePhotoPath: string | null, completionComment: string | null): Promise<void>;
    registerAssistant(username: string, language: Language): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setTaskPinnedStatus(taskId: bigint, isPinned: boolean): Promise<void>;
    setTaskPreference(assistantUsername: string, taskId: bigint, preference: TaskPreference): Promise<void>;
    updateTask(taskId: bigint, title: string, description: string, frequency: TaskFrequency, isWeekly: boolean): Promise<void>;
}
import type { AuditLogAction as _AuditLogAction, AuditLogEntry as _AuditLogEntry, Language as _Language, TaskFrequency as _TaskFrequency, TaskHistoryEntry as _TaskHistoryEntry, TaskPreference as _TaskPreference, Time as _Time, ToDoTask as _ToDoTask, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async checkManagerNotifications(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkManagerNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkManagerNotifications();
            return result;
        }
    }
    async createTask(arg0: string, arg1: string, arg2: TaskFrequency, arg3: boolean): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, to_candid_TaskFrequency_n3(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, to_candid_TaskFrequency_n3(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
    async deleteAssistantData(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAssistantData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAssistantData(arg0);
            return result;
        }
    }
    async getAllAssistants(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAssistants();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAssistants();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTaskHistory(): Promise<Array<TaskHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTaskHistory();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTaskHistory();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTaskHistoryEntries(): Promise<Array<TaskHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTaskHistoryEntries();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTaskHistoryEntries();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTasks(): Promise<Array<ToDoTask>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAuditLog(): Promise<Array<AuditLogEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLog();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLog();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOvertimeEntries(arg0: string): Promise<Array<OvertimeEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOvertimeEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOvertimeEntries(arg0);
            return result;
        }
    }
    async getOvertimeTotals(arg0: string): Promise<OvertimeTotals> {
        if (this.processError) {
            try {
                const result = await this.actor.getOvertimeTotals(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOvertimeTotals(arg0);
            return result;
        }
    }
    async getTask(arg0: bigint): Promise<ToDoTask | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskHistory(arg0: bigint): Promise<Array<TaskHistoryEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskHistory(arg0);
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskHistory(arg0);
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskPreferences(arg0: string): Promise<Array<[bigint, TaskPreference]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskPreferences(arg0);
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskPreferences(arg0);
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async logOvertime(arg0: string, arg1: bigint, arg2: string, arg3: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.logOvertime(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.logOvertime(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async markTaskDone(arg0: bigint, arg1: string | null, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskDone(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskDone(arg0, to_candid_opt_n36(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n36(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerAssistant(arg0: string, arg1: Language): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerAssistant(arg0, to_candid_Language_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerAssistant(arg0, to_candid_Language_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n39(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setTaskPinnedStatus(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskPinnedStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskPinnedStatus(arg0, arg1);
            return result;
        }
    }
    async setTaskPreference(arg0: string, arg1: bigint, arg2: TaskPreference): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setTaskPreference(arg0, arg1, to_candid_TaskPreference_n43(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setTaskPreference(arg0, arg1, to_candid_TaskPreference_n43(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateTask(arg0: bigint, arg1: string, arg2: string, arg3: TaskFrequency, arg4: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskFrequency_n3(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(arg0, arg1, arg2, to_candid_TaskFrequency_n3(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
}
function from_candid_AuditLogAction_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLogAction): AuditLogAction {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AuditLogEntry_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLogEntry): AuditLogEntry {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Language_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Language): Language {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_TaskFrequency_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskFrequency): TaskFrequency {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_TaskHistoryEntry_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskHistoryEntry): TaskHistoryEntry {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_TaskPreference_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskPreference): TaskPreference {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ToDoTask_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToDoTask): ToDoTask {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ToDoTask]): ToDoTask | null {
    return value.length === 0 ? null : from_candid_ToDoTask_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: _AuditLogAction;
    username: string;
    summary: string;
    taskId: bigint;
    userPrincipal: Principal;
    completionComment: [] | [string];
    timestamp: _Time;
    evidencePhotoPath: [] | [string];
}): {
    id: bigint;
    action: AuditLogAction;
    username: string;
    summary: string;
    taskId: bigint;
    userPrincipal: Principal;
    completionComment?: string;
    timestamp: Time;
    evidencePhotoPath?: string;
} {
    return {
        id: value.id,
        action: from_candid_AuditLogAction_n15(_uploadFile, _downloadFile, value.action),
        username: value.username,
        summary: value.summary,
        taskId: value.taskId,
        userPrincipal: value.userPrincipal,
        completionComment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completionComment)),
        timestamp: value.timestamp,
        evidencePhotoPath: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.evidencePhotoPath))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    completedBy: [] | [Principal];
    title: string;
    createdAt: _Time;
    createdBy: Principal;
    lastCompleted: [] | [_Time];
    isWeekly: boolean;
    description: string;
    completionComment: [] | [string];
    completedByUsername: [] | [string];
    frequency: _TaskFrequency;
    evidencePhotoPath: [] | [string];
    completionTimestamp: [] | [_Time];
    isPinned: boolean;
}): {
    id: bigint;
    completedBy?: Principal;
    title: string;
    createdAt: Time;
    createdBy: Principal;
    lastCompleted?: Time;
    isWeekly: boolean;
    description: string;
    completionComment?: string;
    completedByUsername?: string;
    frequency: TaskFrequency;
    evidencePhotoPath?: string;
    completionTimestamp?: Time;
    isPinned: boolean;
} {
    return {
        id: value.id,
        completedBy: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.completedBy)),
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        lastCompleted: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.lastCompleted)),
        isWeekly: value.isWeekly,
        description: value.description,
        completionComment: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completionComment)),
        completedByUsername: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.completedByUsername)),
        frequency: from_candid_TaskFrequency_n23(_uploadFile, _downloadFile, value.frequency),
        evidencePhotoPath: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.evidencePhotoPath)),
        completionTimestamp: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.completionTimestamp)),
        isPinned: value.isPinned
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    action: _AuditLogAction;
    username: string;
    taskId: bigint;
    userPrincipal: Principal;
    timestamp: _Time;
    changeSummary: string;
}): {
    action: AuditLogAction;
    username: string;
    taskId: bigint;
    userPrincipal: Principal;
    timestamp: Time;
    changeSummary: string;
} {
    return {
        action: from_candid_AuditLogAction_n15(_uploadFile, _downloadFile, value.action),
        username: value.username,
        taskId: value.taskId,
        userPrincipal: value.userPrincipal,
        timestamp: value.timestamp,
        changeSummary: value.changeSummary
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    role: _UserRole;
    language: _Language;
}): {
    principal: Principal;
    username: string;
    role: UserRole;
    language: Language;
} {
    return {
        principal: value.principal,
        username: value.username,
        role: from_candid_UserRole_n8(_uploadFile, _downloadFile, value.role),
        language: from_candid_Language_n10(_uploadFile, _downloadFile, value.language)
    };
}
function from_candid_tuple_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [bigint, _TaskPreference]): [bigint, TaskPreference] {
    return [
        value[0],
        from_candid_TaskPreference_n34(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    french: null;
} | {
    dutch: null;
} | {
    english: null;
}): Language {
    return "french" in value ? Language.french : "dutch" in value ? Language.dutch : "english" in value ? Language.english : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taskUpdated: null;
} | {
    taskCreated: null;
} | {
    taskMarkedDone: null;
}): AuditLogAction {
    return "taskUpdated" in value ? AuditLogAction.taskUpdated : "taskCreated" in value ? AuditLogAction.taskCreated : "taskMarkedDone" in value ? AuditLogAction.taskMarkedDone : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
}): TaskFrequency {
    return "monthly" in value ? TaskFrequency.monthly : "daily" in value ? TaskFrequency.daily : "weekly" in value ? TaskFrequency.weekly : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hated: null;
} | {
    preferred: null;
} | {
    neutral: null;
}): TaskPreference {
    return "hated" in value ? TaskPreference.hated : "preferred" in value ? TaskPreference.preferred : "neutral" in value ? TaskPreference.neutral : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    assistant: null;
}): UserRole {
    return "manager" in value ? UserRole.manager : "assistant" in value ? UserRole.assistant : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TaskHistoryEntry>): Array<TaskHistoryEntry> {
    return value.map((x)=>from_candid_TaskHistoryEntry_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToDoTask>): Array<ToDoTask> {
    return value.map((x)=>from_candid_ToDoTask_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLogEntry>): Array<AuditLogEntry> {
    return value.map((x)=>from_candid_AuditLogEntry_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[bigint, _TaskPreference]>): Array<[bigint, TaskPreference]> {
    return value.map((x)=>from_candid_tuple_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_Language_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): _Language {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_TaskFrequency_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFrequency): _TaskFrequency {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_TaskPreference_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPreference): _TaskPreference {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    username: string;
    role: UserRole;
    language: Language;
}): {
    principal: Principal;
    username: string;
    role: _UserRole;
    language: _Language;
} {
    return {
        principal: value.principal,
        username: value.username,
        role: to_candid_UserRole_n41(_uploadFile, _downloadFile, value.role),
        language: to_candid_Language_n37(_uploadFile, _downloadFile, value.language)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Language): {
    french: null;
} | {
    dutch: null;
} | {
    english: null;
} {
    return value == Language.french ? {
        french: null
    } : value == Language.dutch ? {
        dutch: null
    } : value == Language.english ? {
        english: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskFrequency): {
    monthly: null;
} | {
    daily: null;
} | {
    weekly: null;
} {
    return value == TaskFrequency.monthly ? {
        monthly: null
    } : value == TaskFrequency.daily ? {
        daily: null
    } : value == TaskFrequency.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    manager: null;
} | {
    assistant: null;
} {
    return value == UserRole.manager ? {
        manager: null
    } : value == UserRole.assistant ? {
        assistant: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskPreference): {
    hated: null;
} | {
    preferred: null;
} | {
    neutral: null;
} {
    return value == TaskPreference.hated ? {
        hated: null
    } : value == TaskPreference.preferred ? {
        preferred: null
    } : value == TaskPreference.neutral ? {
        neutral: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
